### Create product
POST http://localhost:8080/api/v1/products
Content-Type: application/json

{
  "name": "Mouse Gamer",
  "sku": "MOU-001",
  "quantity": 15
}

### Get all products
GET http://localhost:8080/api/v1/products

### Get product by id
GET http://localhost:8080/api/v1/products/1

### Get product by id 2
GET http://localhost:8080/api/v1/products/2

### Get product by id not found
GET http://localhost:8080/api/v1/products/999